---
title: "About"
author: "George Dalianis"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The goal of this project is to examine the effect of levels of social spending
programs on overall GDP, life expectancy, GDP per capita, and other economic 
variables. The countries studied here will be members of the Organization for
Economic Co-operation and Development (OECD). THe OECD is an international 
economic organization with 36 member countries designed to foster overall 
economic progress and global trade. Its members work together to identify good
economic policies and practices while seeking answers to common problems.

My data comes from several sources. The first source is the Economist 
Intelligence Unit (EIU), a global research/analysis group within the broader 
Economist Group. Here, I found details on every OECD country from 1990 - 2018.
I also loaded four data tables with education, life expectancy, and immigration
statistics. from the OECD itself. My third data source is the gapminder dataset,
which has extensive information on many countries in the world beyond the OECD. 
I've loaded all of these data sources. THE EIU data was very complicated to load
because I needed to condense data from many different sheets into one sheet. The
EIU data is not in table format and is just seperated by commas, so I need to
figure out how to put this data into table format.

Link to repo: https://github.com/georgedalianis7/finalprojectversion1