---
title: "Clean Data"
author: "George Dalianis"
date: "4/24/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
library(scales)
library(gganimate)
library(readr)
library(broom)
```

```{r, load_data}
social_spending <- read.csv("OECD-data/DP_LIVE_19032020165309966.csv") %>%
  clean_names() %>%
  select(location, time, value) %>%
  filter(! location %in% c("EA", "EU"))
```

```{r, graph_data}
data_social <- as.data.frame(social_spending)
x <- data_social %>%
  group_by(location) %>%
  summarize(avg_spending = mean(value))
soc_spending_plot <- ggplot(x, aes(x = reorder(location, avg_spending), y = avg_spending, fill = avg_spending)) + 
  geom_col() + 
  labs(title = "Average Social Benefits to Households in OECD Countries from 1995 to 2018",
       subtitle = "In-cash Benefits, Measured as % of GDP", 
       x = "Country", 
       y = "Average benefits (% of GDP)",
       caption = "Source: OECD National Accounts Statistics") +
  scale_y_continuous(labels = percent_format(scale = 1)) + 
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 9)) + 
  theme(legend.position = "none") + 
  scale_x_discrete(labels = c("MEX" = "Mexico", "KOR" = "Korea", "CHL" = "Chile", "ISR" = "Israel", "ISL" = "Iceland", "AUS" = "Australia", "TUR" = "Turkey", "CAN" = "Canada", "IRL" = "Ireland", "CHE" = "Switzerland", "EST" = "Estonia", "NZL" = "New Zealand", "LVA" = "Latvia", "LTU" = "Lithuania", "NLD" = "Netherlands", "CZE" = "Czech Republic", "JPN" = "Japan", "GBR" = "United Kingdom", "SVK" = "Slovak Republic", "ESP" = "Spain", "HUN" = "Hungary", "NOR" = "Norway", "PRT" = "Portugal", "SWE" = "Sweden", "LUX" = "Luxembourg", "GRC" = "Greece", "POL" = "Poland", "BEL" = "Belgium", "SVN" = "Slovenia", "DNK" = "Denmark", "DEU" = "Germany", "FIN" = "Finland", "ITA" = "Italy", "FRA" = "France", "AUT" = "Austria"))
saveRDS(soc_spending_plot, file = "app/soc_spending_plot.rds")
```

```{r}
oecd_social_benefits.png <- y
ggsave(filename = "oecd_social_benefits.png", device = "png", plot = last_plot())
```


```{r, load_animate}
gdp_per_cap <- read_csv("World_Bank_data/d697f85d-ea2c-4d71-933e-494201e0e9ac_Data.csv") %>%
  clean_names() %>%
  head(-5)
gdp_per_cap0 <- gdp_per_cap[-c(5:9)]
  

pop <- read_csv("World_Bank_data/e254ec52-ffb5-4bb0-9a0b-d8d669a6b94f_Data.csv") %>%
  clean_names() %>%
  head(-5)
pop0 <- pop[-c(5:9)]
```


```{r, tidy_data}
gdp_per_cap1 <- gdp_per_cap0 %>%
  pivot_longer(x1995_yr1995:x2018_yr2018, names_to = "year",
               values_to = "gdp_per_capita",
               names_prefix = "x(.)(.)(.)(.)_yr",
               values_drop_na = TRUE)

pop1 <- pop0 %>%
  pivot_longer(x1995_yr1995:x2018_yr2018, names_to = "year",
               values_to = "population",
               names_prefix = "x(.)(.)(.)(.)_yr",
               values_drop_na = TRUE)

social_spending1 <- social_spending %>%
  rename("country_code" = location,
         "year" = time,
         "pct_soc_spending" = value) 
social_spending1$year <- as.character(social_spending1$year)
graph <- inner_join(gdp_per_cap1, pop1, by = c("country_name", "country_code", "year")) %>%
  select(country_name, country_code, year, gdp_per_capita, population)
graph1 <- inner_join(graph, social_spending1, by = c("country_code", "year"))
```

```{r}
life_expectancy <- read.csv("OECD-data/DP_LIVE_24042020220916159.csv") %>%
  clean_names() %>%
  rename("country_code" = location,
         "year" = time,
         "life_exp" = value) %>%
  select(country_code, year, life_exp)
life_expectancy$year <- as.character(life_expectancy$year)
primary_data <- inner_join(graph1, life_expectancy, by = c("country_code", "year"))
write_rds(primary_data, "app/primary_data.rds")
```


```{r, inequality_data}
gini <- read.csv("OECD-data/DP_LIVE_24042020230247538.csv") %>%
  clean_names() %>% 
  rename("year" = time,
         "gini" = value) %>%
  select(location, year, gini)
write_rds(gini, "app/inequality_data.rds")
```

```{r, education_data}
adult_edu_level <- read.csv("OECD-data/DP_LIVE_25022020171955325.csv") %>%
  clean_names() %>%
  filter(subject == "UPPSRY", ! location %in% c("COL", "ZAF", "CRI")) %>%
  rename("year" = time,
         "pct_secondary" = value)

pct_tertiary_edu <- read.csv("OECD-data/DP_LIVE_25022020171724289.csv") %>%
  clean_names() %>%
  rename("year" = time,
         "pct_tert" = value) %>%
  filter(subject == "25_34", ! location %in% c("COL", "ZAF", "CRI"))

education <- inner_join(adult_edu_level, pct_tertiary_edu, by = c("location", "year")) %>%
  select(location, year, pct_secondary, pct_tert)
write_rds(education, "app/education_data.rds")
```

```{r, interactive_data}
options(scipen = 10000)
primary_data$year <- as.integer(primary_data$year)
life_exp_anim <- primary_data %>%
  ggplot(aes(x = gdp_per_capita, y = life_exp, size = population, color = country_name)) + 
  geom_point(show.legend = FALSE, alpha = 0.7) + 
  scale_color_viridis_d() + scale_x_log10() +
  theme_classic() +
  transition_time(year) + 
  labs(title = "OECD Development 1995-2018",
       subtitle = "Year: {frame_time}",
       x = "GDP per capita (US$, PPP adjusted)",
       y = "Life Expectancy (Years)",
       caption = "Source: OECD and World Bank") + 
  shadow_mark()
anim_save(filename = "life_exp_animation", animation = life_exp_anim, path = "app")
```

```{r}
social_exp <- read.csv("OECD-data/DP_LIVE_26042020204617582.csv") %>%
  clean_names() %>%
  filter(time <= 2015) %>%
  select(location, time, value) %>%
  rename("soc_exp_pctgdp" = value)
unemployment_benefits <- read.csv("OECD-data/DP_LIVE_26042020204828426.csv") %>%
  clean_names() %>%
  select(location, time, value) %>%
  rename("unemp_expenditure" = value)
pension_spending <- read.csv("OECD-data/DP_LIVE_26042020204940396.csv") %>%
  clean_names() %>%
  filter(time <= 2015) %>%
  select(location, time, value) %>%
  rename("pension_spending" = value)
joined_socialp1 <- inner_join(social_exp, unemployment_benefits, by = c("location", "time"))
final_joined_social <- inner_join(joined_socialp1, pension_spending, by = c("location", "time"))
```

```{r}
write_rds(final_joined_social, "app/final_socialspending_data.rds")
```

```{r, soc_regreggion}
soc_regression <- primary_data %>%
ggplot(aes(x = pct_soc_spending, y = gdp_per_capita)) + 
  geom_point() + 
  scale_x_log10() + 
  geom_smooth(method = "lm", se = FALSE) + 
  theme_classic() + 
  labs(title = "Effect of Social Programs on GDP per capita",
       subtitle = "Benefits measured in-cash, 2010 Dollars",
       x = "Social Spending as % of GDP",
       y = "GDP per capita(2010 Dollars)")
saveRDS(soc_regression, file = "app/soc1_regression.rds")
model <- lm(gdp_per_capita ~ pct_soc_spending, data = primary_data) %>%
  tidy(conf.int = TRUE) 
model
```

```{r, life_regression}
life_regression <- primary_data %>%
  ggplot(aes(x = pct_soc_spending, y = life_exp)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE) + 
  scale_x_log10() + 
  theme_classic() +
  labs(title = "Effect of Social Spending on Life Expectancy",
       subtitle = "Benefits Measured in-cash, 2010 Dollars",
       x = "Social Spending as a % of GDP",
       y = "Life Expectancy")
saveRDS(life_regression, file = "app/life_exp_regression.rds")
model1 <- lm(life_exp ~ pct_soc_spending, data = primary_data) %>%
  tidy(conf.int = TRUE) 
model1
```

```{r, inequality_regression}
x <- inequality_data %>%
  filter(year == 2015)
y <- final_socialspending_data %>%
  filter(time == 2015)
inequality <- inner_join(x, y, by = "location")
inequality_regression <- ggplot(inequality, aes(x = soc_exp_pctgdp, y = gini)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE) +
  theme_classic() +
  labs(title = "Effect of Social Spending on Economic Inequality",
       subtitle = "Measured by Gini Coefficient: Number between 0 and 1, a higher coefficient signals greater inequality",
       x = "Social Spending as a % of GDP",
       y = "Gini Coefficient")
saveRDS(inequality_regression, file = "app/ineq_regression.rds")
```

```{r}
inequality1 <- inequality %>%
  filter(year == 2015)
model1 <- lm(gini ~ soc_exp_pctgdp, data = inequality) %>%
  tidy(conf.int = TRUE) 
model1
```

```{r}
labor_market <- read.csv("OECD-data/EPL_OV_27042020040430416.csv") %>%
  clean_names() %>%
  select(country, country_2, time, value) %>%
  rename("country_name" = country_2,
         "year" = time)
primary_data$year <- as.integer(primary_data$year)
abc <- inner_join(labor_market, primary_data, by = c("country_name", "year"))
market_regression <- ggplot(abc, aes(x = pct_soc_spending, y = value)) + 
    geom_jitter(height = 0.05) + geom_smooth(method = "lm", se = FALSE) + theme_classic() +
    labs(title = "Effect of Social Spending Programs on Labor Market Freedom",
         subtitle = "Labor Market Regulation Measured on 1-5 Scale: Higher Number Means Comparatively Lower Freedom",
         x = "Level of Social Spending as % of GDP",
         y = "Degree of Labor Market Regulation")
  saveRDS(market_regression, file = "app/mark_regression.rds")
```

```{r}
model1 <- lm(value ~ pct_soc_spending, data = abc) %>%
  tidy(conf.int = TRUE) 
model1
```

```{r, facet_graph}
primary_data$year <- as.numeric(primary_data$year)
richest_poorest <- primary_data %>%
  group_by(year) %>%
  filter(year <= 2017) %>%
  filter(country_name %in% c("Luxembourg", "Greece")) %>%
  ggplot(aes(x = year, y = gdp_per_capita, color = country_name)) + 
  geom_line() + 
  geom_vline(xintercept = 2008, linetype = "dashed") + 
  scale_color_manual(labels = c("Greece", "Luxembourg"),
                     values = c("blue", "red")) +
  geom_text(aes(x = 2007.5, label = "2008 Recession", y = 60000), angle = 90, color = "black") +
  theme_classic() + 
  labs(title = "Richest and Poorest OECD Countries in 2016",
       subtitle = "Measured by GDP Per Capita, US$",
       x = "Year",
       y = "GDP Per Capita, US$",
       color = "Country")
```

```{r}
abc2 <- abc %>%
  rename("location" = country,
         "time" = year) %>%
  select(time, location, value)
ad <- right_join(final_socialspending_data, abc2, by = c("location","time")) %>%
  na.omit()
  
```

```{r}
ad1 <- ad %>%
  filter(time <= 2015) %>%
  group_by(time) %>%
  nest()
x <- ad1 %>%
  mutate(mod = map(data, ~ lm(pension_spending ~ value, data = .)),
         reg_results = map(mod, ~ tidy(.)),
         coef = map_dbl(reg_results, ~ filter(., term == "value") 
                        %>% pull(estimate)),
         se = map_dbl(reg_results, ~ filter(., term == "value")
                      %>% pull(std.error)),
         upper = coef + 1.96 * se,
         lower = coef - 1.96 * se)
 ggplot(x, aes(x = time, y = coef)) +
  geom_point(color = "blue") +
  geom_errorbar(aes(x = time, ymin = lower, ymax = upper), color = "blue") +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = "dashed") + 
  labs(title = "Effect of Labor Market Regulation on GDP Per Capita",
       subtitle = "Controlling for Social Spending",
       x = "Year",
       y = "Coefficient")
```

```{r, migration_data}
migration <- read.csv("OECD-data/DP_LIVE_28042020023147434.csv") %>%
  clean_names() %>%
  select(location, time, value) %>%
  rename("pct_foreignborn" = value)
joined_migration <- inner_join(migration, final_socialspending_data, by = c("location", "time"))
migration_graph <- ggplot(joined_migration, aes(x = soc_exp_pctgdp, y = unemp_expenditure)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_classic() +
  labs(title = "Public Unemployment Spending",
       subtitle = "Includes Redundancy Payments from Public Funds",
       x = "Social Expenditure as a % of GDP",
       y = "Unemployment Expenditure as % of GDP")
saveRDS(migration_graph, file = "app/mig_graph.rds")
model1 <- lm(unemp_expenditure ~ soc_exp_pctgdp, data = joined_migration) %>%
  tidy(conf.int = TRUE) 
model1
```


```{r}
lol <- joined_migration %>%
  filter(time <= 2015) %>%
  group_by(time) %>%
  nest()
w <- lol %>%
  mutate(mod = map(data, ~ lm(soc_exp_pctgdp ~ pct_foreignborn, data = .)),
         reg_results = map(mod, ~ tidy(.)),
         coef = map_dbl(reg_results, ~ filter(., term == "pct_foreignborn") 
                        %>% pull(estimate)),
         se = map_dbl(reg_results, ~ filter(., term == "pct_foreignborn")
                      %>% pull(std.error)),
         upper = coef + 1.96 * se,
         lower = coef - 1.96 * se)
 migration_error <- ggplot(x, aes(x = time, y = coef)) +
  geom_point(color = "blue") +
  geom_errorbar(aes(x = time, ymin = lower, ymax = upper), color = "blue") +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = "dashed") + 
  labs(title = "Effect of Foreign Born Population on GDP Social Spending",
       subtitle = "Controlling for Unemployment",
       x = "Year",
       y = "Coefficient")
 saveRDS(migration_error, file = "app/migrationd.rds")
 model1 <- lm(soc_exp_pctgdp ~ pct_foreignborn, data = joined_migration) %>%
  tidy(conf.int = TRUE) 
model1
```


```{r}
pension_graph <- ggplot(joined_migration, aes(x = soc_exp_pctgdp, y = pension_spending)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_classic() +
  labs(title = "Pension Spending",
       subtitle = "Includes Lump Sum Payments",
       x = "Social Expenditure as a % of GDP",
       y = "Pension Spending as % of GDP")
saveRDS(pension_graph, file = "app/pen_graph.rds")
```

```{r, migration2_graph}
migration2_graph <- ggplot(joined_migration, aes(x = pct_foreignborn, y = soc_exp_pctgdp)) + 
  geom_jitter(width = 0.1) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_classic() +
  labs(title = "Foreign-born Citizens",
       subtitle = "Includes Individuals Born Abroad who Currently Reside in OECD Country",
       x = "Foreign Born Individuals as % of Total Population",
       y = "Social Expenditure as a % of GDP")
saveRDS(migration2_graph, file = "app/mig_2.rds")
```


```{r, my_choices}
choices <- primary_data %>%
  filter(year == 2016) %>%
  select(country_name) %>%
  rename("Name" = country_name)
write_rds(choices, "app/choices_data.rds")
```

